blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/migtorr/Ryujinx-Steam-Deck-compatibilty-list/discussions
    about: Please use GitHub discussions for feature requests.
